# Generated by Django 4.2 on 2023-04-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
