# Generated by Django 4.2 on 2023-05-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer',
            field=models.IntegerField(default=0),
        ),
    ]
