# Generated by Django 4.2 on 2023-04-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_ip_order_is_returned_order_order_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Ordered',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default=False),
        ),
    ]
